import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    environment: 'jsdom',
    tags: [
      { name: 'M1UC35', description: 'Login stores tokens and redirects user' },
      { name: 'M1UC36', description: 'Registration completes and redirects to login' },
      { name: 'M1UC37', description: 'Refresh token stores new tokens' },
      { name: 'M1UC38', description: 'Logout clears tokens from localStorage' },
      { name: 'M1UC39', description: 'isAuthenticated checks token validity' },
      { name: 'M1UC46', description: 'Admin creates user and invite URL is displayed' },
      { name: 'M1UC47', description: 'Admin regenerates invite and new URL is displayed' },
      { name: 'M1UC48', description: 'User without valid token is redirected to login' },
      { name: 'M1UC49', description: 'Admin page load fetches and returns all users' },
      { name: 'M1.1UC3', description: 'Password strength checklist updates in real time as user types' },
      { name: 'M1.1UC4', description: 'Form submits without client-side blocking when all rules satisfied' },
      { name: 'M1.1UC9', description: 'Forgot-password page transitions to success state after submission' },
      { name: 'M1.1UC10', description: 'Reset-password page resets password and redirects to login on success' },
      { name: 'M1.1UC11', description: 'Reset-password page shows invalid/expired state for bad token' },
      { name: 'M1.1UC12', description: 'Admin updates user roles via PATCH and receives 200 with updated user' },
      { name: 'M1.1UC13', description: 'Non-admin receives 403 on PATCH /api/users/{userId}' },
      { name: 'M1.1UC14', description: 'Edit button transitions active user row to inline role-checkbox edit mode' },
      { name: 'M1.1UC15', description: 'Saving inline edit sends PATCH and returns row to display mode with updated badges' },
      { name: 'M1.1UC23', description: 'Admin creates user with multiple roles; all roles are persisted' },
      { name: 'M1.1UC24', description: 'Admin selects multiple roles in create-user form; all role badges appear for new user' },
      { name: 'M1.1UC18', description: 'Deactivate button opens confirmation modal showing user email; Cancel dismisses with no action' },
      { name: 'M1.1UC19', description: 'Confirming deactivation calls DELETE endpoint; modal closes and row is removed from User Directory table' },
      { name: 'M1.1UC27', description: 'Deactivated user row renders a Delete button' },
      { name: 'M1.1UC28', description: 'Permanent-delete modal Delete button is disabled until email is entered' },
      { name: 'M1.1UC29', description: 'Typing the correct email in permanent-delete modal enables the Delete button' },
      { name: 'M1.1UC30', description: 'Confirming permanent delete calls DELETE /permanent; modal closes and row is removed' },
      { name: 'M1.1UC31', description: 'Cancel on permanent-delete modal closes it with no API call' },
      { name: 'M1.1UC32', description: 'deleteUser service calls DELETE /api/users/{id}/permanent and invalidates cache' },
      { name: 'M1.1UC38', description: 'Deactivated user row renders Activate button to the left of Delete' },
      { name: 'M1.1UC39', description: 'Clicking Activate dispatches user-activate-requested; on success table reloads showing Active row' },
      { name: 'M1.1UC40', description: 'activateUser service calls PATCH /api/users/{id}/activate and invalidates cache' },
    ],
  },
})
