import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    environment: 'jsdom',
    tags: [
      { name: 'M1UC35', description: 'Login stores tokens and redirects user' },
      { name: 'M1UC36', description: 'Registration completes and redirects to login' },
      { name: 'M1UC37', description: 'Refresh token stores new tokens' },
      { name: 'M1UC38', description: 'Logout clears tokens from localStorage' },
      { name: 'M1UC39', description: 'isAuthenticated checks token validity' },
      { name: 'M1UC46', description: 'Admin creates user and invite URL is displayed' },
      { name: 'M1UC47', description: 'Admin regenerates invite and new URL is displayed' },
      { name: 'M1UC48', description: 'User without valid token is redirected to login' },
      { name: 'M1UC49', description: 'Admin page load fetches and returns all users' },
      { name: 'M1.1UC3', description: 'Password strength checklist updates in real time as user types' },
      { name: 'M1.1UC4', description: 'Form submits without client-side blocking when all rules satisfied' },
      { name: 'M1.1UC9', description: 'Forgot-password page transitions to success state after submission' },
      { name: 'M1.1UC10', description: 'Reset-password page resets password and redirects to login on success' },
      { name: 'M1.1UC11', description: 'Reset-password page shows invalid/expired state for bad token' },
      { name: 'M1.1UC12', description: 'Admin updates user roles via PATCH and receives 200 with updated user' },
      { name: 'M1.1UC13', description: 'Non-admin receives 403 on PATCH /api/users/{userId}' },
      { name: 'M1.1UC14', description: 'Edit button transitions active user row to inline role-checkbox edit mode' },
      { name: 'M1.1UC15', description: 'Saving inline edit sends PATCH and returns row to display mode with updated badges' },
      { name: 'M1.1UC23', description: 'Admin creates user with multiple roles; all roles are persisted' },
      { name: 'M1.1UC24', description: 'Admin selects multiple roles in create-user form; all role badges appear for new user' },
      { name: 'M1.1UC18', description: 'Deactivate button opens confirmation modal showing user email; Cancel dismisses with no action' },
      { name: 'M1.1UC19', description: 'Confirming deactivation calls DELETE endpoint; modal closes and row is removed from User Directory table' },
      { name: 'M1.1UC27', description: 'Deactivated user row renders a Delete button' },
      { name: 'M1.1UC28', description: 'Permanent-delete modal Delete button is disabled until email is entered' },
      { name: 'M1.1UC29', description: 'Typing the correct email in permanent-delete modal enables the Delete button' },
      { name: 'M1.1UC30', description: 'Confirming permanent delete calls DELETE /permanent; modal closes and row is removed' },
      { name: 'M1.1UC31', description: 'Cancel on permanent-delete modal closes it with no API call' },
      { name: 'M1.1UC32', description: 'deleteUser service calls DELETE /api/users/{id}/permanent and invalidates cache' },
      { name: 'M1.1UC38', description: 'Deactivated user row renders Activate button to the left of Delete' },
      { name: 'M1.1UC39', description: 'Clicking Activate dispatches user-activate-requested; on success table reloads showing Active row' },
      { name: 'M1.1UC40', description: 'activateUser service calls PATCH /api/users/{id}/activate and invalidates cache' },
      { name: 'M1.1UC20', description: 'Create-user success banner appears with invite link and Copy Link button' },
      { name: 'M1.1UC21', description: 'Regenerate-invite compact banner appears with new invite link and Copy Link button' },
      { name: 'M1.1UC22', description: 'Status filter filters User Directory rows client-side; All restores full list' },
      { name: 'M1.2UC1', description: 'tryRefresh() distinguishes confirmed rejection from unexpected failure and dedupes concurrent calls' },
      { name: 'M1.2UC2', description: 'render() shows a retry message on refresh failure and cancels a stale retry timer when navigation triggers a new render first' },
      { name: 'M1.4UC6', description: 'GetOwnSessions returns only the caller own sessions with the current session identifiable' },
      { name: 'M1.4UC7', description: 'Revoking an own session or all own other sessions never revokes the current session' },
      { name: 'M1.4UC8', description: 'Admin global session list spans every user with the owning user identified' },
      { name: 'M1.4UC9', description: 'Admin can revoke a specific session or every session except their own current one' },
      { name: 'M1.4UC11', description: 'Viewer own current session is distinguishable in the My Active Sessions and Global Session Management views' },
      { name: 'M1.4UC12', description: 'The sidebar appears alongside the top nav bar on every authenticated page' },
      { name: 'M1.5UC15', description: 'Activity Log page loads and displays a paginated table of audit events, with an empty state when none match' },
      { name: 'M1.5UC16', description: 'Applying filters on the Activity Log page updates results and resets pagination to page 1' },
      { name: 'M1.5UC17', description: 'A non-admin user navigating to the Activity Log page is redirected to / and no audit data is rendered' },
      { name: '162UC1', description: 'Each confirmation modal adopts the shared modal-chrome stylesheet and no longer declares the extracted selectors locally' },
    ],
  },
})
