using PanoramaMusic.Students.Application.Requests.GuardianRelationships;

namespace PanoramaMusic.Students.Application.Commands.GuardianRelationships;

public sealed record CreateGuardianRelationshipCommand(CreateGuardianRelationshipRequest Request);